{
  "name": "fyp-portfolio",
  "version": "1.0.0",
  "description": "FYP Portfolio - Autonomous Medicine Delivery Robot - Air University P2222",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.18.2"
  }
}
